# Generates src/Generated/BuildInfo.cs, so the binary can report which version
# and which build it is. Regenerated on every build; not committed.
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$here = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
$root = Split-Path -Parent $here
. (Join-Path $root 'scripts\build-config.ps1')

$generatedDir = Join-Path $root 'src\Generated'
New-Item -ItemType Directory -Force -Path $generatedDir | Out-Null

$buildDate = Get-Date -Format 'yyyy-MM-dd'

# Record the commit when building from a checkout; harmless when git is absent.
$commit = ''
try {
    if (Get-Command git -ErrorAction SilentlyContinue) {
        $commit = (& git -C $root rev-parse --short HEAD 2>$null)
        if ($LASTEXITCODE -ne 0) { $commit = '' }
    }
} catch { $commit = '' }
if (-not $commit) { $commit = 'unknown' }

$content = @"
// Generated by scripts/generate-build-info.ps1 - do not edit, do not commit.
namespace ProxyPacToggler
{
    internal static class BuildInfo
    {
        public const string Version = "$Version";
        public const string Date = "$buildDate";
        public const string Commit = "$($commit.Trim())";
    }
}
"@

$outFile = Join-Path $generatedDir 'BuildInfo.cs'
Set-Content -Path $outFile -Value $content -Encoding UTF8
Write-Host "Generated BuildInfo.cs (version: $Version, date: $buildDate, commit: $($commit.Trim()))"
